var _ = require('lodash');

var responseCode = {
  INVALID_TOKEN: 100,
  INVALID_REQUEST: 101,
  INVALID_PARAMS: 102,
  INVALID_EMAIL: 103,
  ACCOUNT_EXIST: 104,
  EMAIL_EXIST: 105,
  ACCESS_TOKEN_INVALID: 106,
  ACCOUNT_NOT_EXIST: 107,
  REDIS:108,
  SERVER_MAINTENANCE: 109,
  GET_SUCCESS: 100000,
  GET_FAIL: 100001,
  NORMAL_STATE: 400000,
  FORCE_UPDATE_STATE: 400001,
  INFORMATION_UPDATE_STATE: 400002,
  AUTHORIZE_SUCCESS: 500000,
  AUTHORIZE_FAIL: 500001,
  REGISTER_SUCCESS: 500002,
  REGISTER_FAIL: 500003,
  ACCOUNT_NOT_VALID: 500003,
  VERIFY_ACCESS_TOKEN_SUCCESS: 500010,
  VERIFY_ACCESS_TOKEN_FAIL: 500011,
  GET_INFO_SUCCESS: 500020,
  GET_INFO_FAIL: 500021,
  CHANGE_PASSWORD_SUCCESS: 500022,
  CHANGE_PASSWORD_FAIL: 500023,
  PASSWORD_NOT_MATCH: 500024,
  LOGOUT_SUCCESS: 500025,
  LOGOUT_FAIL: 500026,
  UPDATE_CHANNEL_SUCCESS: 500027,
  UPDATE_CHANNEL_FAIL: 500028,
  AUTHORIZE_FACEBOOK_SUCCESS: 500030,
  AUTHORIZE_FACEBOOK_FAIL: 500031,
  AUTHORIZE_GOOGLE_SUCCESS: 500032,
  AUTHORIZE_GOOGLE_FAIL: 500033,
  REGISTER_QUICKLY_SUCCESS: 500034,
  REGISTER_QUICKLY_FAIL: 500035,
  PAYMENT_LIST_SUCCESS: 500040,
  PAYMENT_LIST_FAIL: 500041,
  PAYMENT_SUCCESS: 500042,
  PAYMENT_FAIL: 500043,
  SSO_SUCCESS: 500051,
  SSO_FAIL: 500052,
  MAPPING_ACCOUNT_SUCCESS: 500060,
  MAPPING_ACCOUNT_FAIL: 500061,
  ACCOUNT_LOCKED: 500062,
  ACCOUNT_NORMAL: 500063,
  UNLOCK_FAIL: 500064,
  UNLOCK_SUCCESS: 500065,
  INVALID_RES_DEVICE: 500066,
  INVALID_RES_GA: 500067,
  INVALID_RES_CACHE: 500068,
  UPDATE_DEVICE_INFO_SUCCESS: 500069,
  UPDATE_DEVICE_INFO_FAIL: 500070,
  SEARCH_GRAPH_FAIL: 500000,
  SEARCH_GRAPH_SUCCESS: 500001
}

var responseMessage = {
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_PARAMS: "INVALID_PARAMS",
  INVALID_TOKEN: "INVALID_TOKEN",
  GET_SUCCESS: "Lấy thông tin thành công",
  GET_FAIL: "Lấy thông tin thất bại",
  NORMAL_STATE: "Trạng thái bình thường",
  AUTHORIZE_SUCCESS: "Đăng nhập thành công",
  AUTHORIZE_FAIL: "Đăng nhập thất bại",
  REGISTER_SUCCESS: 'Đăng ký tài khoản thành công',
  REGISTER_FAIL: 'Đăng ký tài khoản thất bại',
  ACCOUNT_NOT_VALID: 'Tài khoản chỉ được phép có chữ và số',
  INVALID_EMAIL: "Email không hợp lệ",
  ACCOUNT_EXIST: "Tài khoản đã tồn tại",
  EMAIL_EXIST: "Email đã tồn tại",
  ACCESS_TOKEN_INVALID: 'Chuỗi xác thực hết hạn',
  VERIFY_ACCESS_TOKEN_SUCCESS: "Chứng thực hợp lệ",
  VERIFY_ACCESS_TOKEN_FAIL: "Chứng thực không hợp lệ",
  GET_INFO_SUCCESS: "Thông tin tài khoản",
  GET_INFO_FAIL: "Không tìm thấy thông tin tài khoản",
  CHANGE_PASSWORD_SUCCESS: 'Đổi mật khẩu thành công',
  CHANGE_PASSWORD_FAIL: 'Đổi mật khẩu thất bại',
  PASSWORD_NOT_MATCH: 'Mật khẩu cũ không trùng khớp',
  LOGOUT_SUCCESS: 'Thoát tài khoản thành công',
  LOGOUT_FAIL: 'Thoát tài khoản thất bại',
  UPDATE_CHANNEL_SUCCESS: 'Cập nhật channel thành công',
  UPDATE_CHANNEL_FAIL: 'Cập nhật channel thất bại',
  AUTHORIZE_FACEBOOK_SUCCESS: 'Đăng nhập facebook thành công',
  AUTHORIZE_FACEBOOK_FAIL: 'Đăng nhập facebook thất bại',
  AUTHORIZE_GOOGLE_SUCCESS: 'Đăng nhập google thành công',
  AUTHORIZE_GOOGLE_FAIL: 'Đăng nhập google thất bại',
  REGISTER_QUICKLY_SUCCESS: 'Đăng ký thành công',
  REGISTER_QUICKLY_FAIL: 'Đăng ky thất bại',
  PAYMENT_SUCCESS: 'Thanh toán thành công',
  PAYMENT_FAIL: 'Thanh toán thất bại',
  ACCOUNT_NOT_EXIST: 'Tài khoản không tồn tại',
  REDIS: 'Redis cache',
  SERVER_MAINTENANCE: 'Server đang bảo trì',
  SSO_SUCCESS: 'Đăng nhập thành công',
  SSO_FAIL: 'Đăng nhập thất bại',
  MAPPING_ACCOUNT_SUCCESS: 'Cập nhật thành công',
  MAPPING_ACCOUNT_FAIL: 'Cập nhật thất bại',
  ACCOUNT_LOCKED: 'Tài khoản đã bị khóa',
  ACCOUNT_NORMAL: 'Tài khoản hoạt động bình thường',
  UNLOCK_FAIL: 'Mở khóa tài khoản thất bại',
  UNLOCK_SUCCESS: 'Mở khóa tài khoản thành công',
  INVALID_RES_DEVICE: '[1] Thiết bị của bạn đã sử dụng hết số lần tạo tài khoản',
  INVALID_RES_GA: '[2] Thiết bị của bạn đã sử dụng hết số lần tạo tài khoản',
  INVALID_RES_CACHE: 'Hiện tại không thể tạo thêm tài khoản, vui lòng đăng nhập bằng Facebook hoặc G+',
  UPDATE_DEVICE_INFO_SUCCESS: 'Cập nhật thông tin thiết bị thành công',
  UPDATE_DEVICE_INFO_FAIL: 'Cập nhật thông tin thiết bị thất bại',
  SEARCH_GRAPH_FAIL: 'SEARCH_GRAPH_FAIL',
  SEARCH_GRAPH_SUCCESS: 'SEARCH_GRAPH_SUCCESS'
}

module.exports = {
  getCode(desc) {
    return _.isUndefined(responseCode[desc]) ? 100 : responseCode[desc];
  },

  getMessage(desc){
    return _.isUndefined(responseMessage[desc]) ? responseCode[desc] : responseMessage[desc];
  }
}
